name: Pull Request Workflow Target Merge

on:
  pull_request_target:

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the pull request code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: Set up Node.js
        uses: actions/setup-node@v4

      # Step 2: Echo a message
      - name: Say hello
        run: |
          echo "Hello, this is a pull request target workflow!"
          npm run poc
          
